spring.application.name=miniTippSpiel
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tippspiel_db
spring.datasource.username=check24_user
spring.datasource.password=check24_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
